# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Angie Wang
email: angiezwang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Angie Wang is an award-winning multimedia journalist covering crime, education and immigration at Columbia Journalism School. She worked as a breaking news intern for the Associated Press in Phoenix after receiving her bachelor’s degree in communication at UCLA. During her undergraduate years, she served as a news editor and photo editor at the Daily Bruin. She was also selected as a fellow by the Asian American Journalists Association in 2016.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://angie.wang" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: byangiewang
instagram_username:  angiewang.jpg

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
      authors: ["Angie Wang"]
      photo:
        thumbnail: true